version: "3.8"

services:
  remix-social-media-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      remix-social-media-db:
        condition: service_healthy
    env_file:
      - .env

  remix-social-media-db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [
          "CMD-SHELL",
          "mysql -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1' && \
          mysql -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SHOW DATABASES LIKE \"$MYSQL_DATABASE\";' | grep $MYSQL_DATABASE",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db-data:
